# Generated by Django 2.1.7 on 2019-04-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desccription',
            new_name='description',
        ),
    ]
